"""Добавлена модель задач

Revision ID: c9c51bcd82f6
Revises: fb9b97d5b5db
Create Date: 2025-07-24 00:04:43.741274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c51bcd82f6'
down_revision = 'fb9b97d5b5db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('client',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('client',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               nullable=False)

    op.drop_table('task')
    # ### end Alembic commands ###
