"""Добавлены facade_type и area

Revision ID: 43e1862c2079
Revises: 3b523c03c890
Create Date: 2025-07-25 23:21:16.967771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e1862c2079'
down_revision = '3b523c03c890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facade_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('area', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('area')
        batch_op.drop_column('facade_type')

    # ### end Alembic commands ###
