"""обавлено поле polishing_1

Revision ID: 6a88401b3279
Revises: 43e1862c2079
Create Date: 2025-08-29 22:25:20.999560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a88401b3279'
down_revision = '43e1862c2079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('polishing_1', sa.Boolean(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('client',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('client',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('polishing_1')

    # ### end Alembic commands ###
