"""Добавлен этап оплаты

Revision ID: 822be4c25030
Revises: b5829f627ec6
Create Date: 2025-07-18 21:57:29.964967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822be4c25030'
down_revision = 'b5829f627ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.drop_column('prepayment')
        batch_op.drop_column('postpayment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postpayment', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('prepayment', sa.FLOAT(), nullable=True))
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
